version: '3.8'  # or the version that matches your environment

services:
  etch-a-sketch-gui:
    build:
      context: etch-a-sketch-gui
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://${HOST_IP}:5010  # Pass the build arg
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://${HOST_IP}:5010  # Use host IP for API URL

  etch-a-sketch-server:
    build:
      context: .  # Set the build context to the parent directory
      dockerfile: etch-a-sketch-server/Dockerfile
    ports:
      - "5005:5005"
      - "5010:5010"
    tty: true