version: '3.8' # or the version that matches your environment

services:
  etch-a-sketch-gui:
    build:
      context: etch-a-sketch-gui
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://${HOST_IP}:5010 # Pass the build arg
    ports:
      - "80:80"

  etch-a-sketch-server:
    build:
      context: etch-a-sketch-server
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 0
    ports:
      - "5005:5005"
      - "5010:5010"
    runtime: nvidia # ensures that the GPU is accessible
    stdin_open: true # equivalent to -it in docker run
    tty: true
