# Description: Configuration file for etch server

# Server parameters
server:
  host: "192.168.10.5"
  # Server port
  port: 5010
  stream_port: 5005
  max_workers: 12

# Drawing parameters
drawing:
  video_generation:
    frame_rate: 8
  # Options are "potrace" or "vtracer"
  pipeline: "vtracer"
  width: 125
  height: 85.9375
  feed_rate: 14000
  acceleration: 13000
  # Zero position in mm
  origin_x: 2.5
  origin_y: 1.3

robot:
  # 18:81
  gear_ratio: 0.22222222222
  # 0.1858 mm per rad
  mm_to_knob_rad: 0.1858
  left_right_backlash_mm: 1.45
  up_down_backlash_mm: 1.87
  backlash_compensation_radpersec: 130.0
  backlash_acceleration: 9000
  max_acceleration: 25000
  error_tolerance_mm: 0.8 # mm
  cooldown_multiplier: 0.75
