# Description: Configuration file for etch server

# Server parameters
server:
  host: "192.168.10.5"
  # Server port
  port: 5010
  stream_port: 5005

video_generation:
  frame_rate: 8

# Drawing parameters
drawing:
  width: 130
  height: 89.375
  feed_rate: 14000
  acceleration: 16000
  # Zero position in mm
  origin_x: 2.9
  origin_y: 1.5

robot:
  # 18:81
  gear_ratio: 0.22222222222
  # 0.1858 mm per rad
  mm_to_knob_rad: 0.1858
  left_right_backlash_mm: 2.0
  up_down_backlash_mm: 2.6
  backlash_compensation_radpersec: 130.0
  backlash_acceleration: 9000
  max_acceleration: 25000
  error_tolerance_mm: 0.8 # mm
  cooldown_multiplier: 0.75
